### PR TITLE
Update v1.8.0

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes https://github.com/conda-forge/dbt-bigquery-feedstock/pull/35

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Thanks so much @rxm7706! Could I add you as a maintainer on the rest of the adapters and on dbt (-core)?

**Comment by rxm7706** [comment]
> Thanks so much @rxm7706! Could I add you as a maintainer on the rest of the adapters and on dbt (-core)?

Sure - Happy to help, would be good if we can get all the plugins recipes to include @conda-forge/dbt as maintainer - I think I have a few where I am the only maintainer - dbt-spark, dbt-dremio -- maybe we can get the community to start including the @conda-forge/dbt as maintainers - its a good thing. especially since we have the founders of dbt-labs as maintainers on dbt (-core)

**Comment by maresb** [comment]
@rxm7706, I haven't seen this group contributor construction before on conda-forge. While I do seem to have push access to dbt-adapters-feedstock, I noticed that the README doesn't list me or @conda-forge/dbt as maintainers. I'm wondering if it might be glitchy.

Also, I'm asking in the conda-forge Matrix/Element channel about whether we need to delete the `dbt-feedstock` and recreate it under `dbt-core-feedstock` since it's been split, so the future of the group might be slightly uncertain

**Comment by rxm7706** [comment]
Interesting - Perhaps the next rerender will fix it - see https://github.com/conda-forge/qt-feedstock it does list Feedstock Maintainers as [@conda-forge/qt-main](https://github.com/conda-forge/qt-main/) based on https://github.com/conda-forge/qt-feedstock/blob/main/recipe/meta.yaml#L91 & https://github.com/conda-forge/qt-main-feedstock/blob/main/recipe/meta.yaml#L229

and yes we could wait to see what happens to dbt-feedstock



> @rxm7706, I haven't seen this group contributor construction before on conda-forge. While I do seem to have push access to dbt-adapters-feedstock, I noticed that the README doesn't list me or @conda-forge/dbt as maintainers. I'm wondering if it might be glitchy.
> 
> Also, I'm asking in the conda-forge Matrix/Element channel about whether we need to delete the `dbt-feedstock` and recreate it under `dbt-core-feedstock` since it's been split, so the future of the group might be slightly uncertain

**Pull request merged**
